# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 21600s # 6 hours - builds for each arch take time and is slower on Cloud Build
# this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
# or any new substitutions added in the future.
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:latest"
    entrypoint: make
    env:
      - TAG=$_GIT_TAG
    args:
      - all-push
substitutions:
  _GIT_TAG: "0.0.0" # default value, this is substituted at build time
